### PR TITLE
assorted bugfixes

### LINKED ISSUE #1126: [Campaigns Wizard] Multiple campaigns autocomplete UI
**Describe the issue**
Seems to be some trouble maintaining labels in the autcomplete UI when selecting more than one campaign. Example:

https://d.pr/i/k51qPz

The bug seems to be purely visual and doesn't affect the actual assignment of campaign terms, or throw any JS console errors.

**To Reproduce**
1. Go to **Newspack > Campaigns**
2. Create or edit a campaign in the wizard
3. Attempt to add more than one campaign term in the "Campaigns" field
4. Observe error

### LINKED ISSUE #1148: Site Design Wizard: Tagline populates 'Copyright' field
**Describe the bug**
When you run through the Design Wizard, if the site has a tagline the value ends up saved as the 'Copyright Information'(under Customizer > Footer Settings).

The copyright will display the Site Name by default unless a value is added here; it would probably make the most sense to leave this field blank as part of the design wizard, and leave it to the publisher to edit/override if needed.

### PR DESCRIPTION
**Pull request by adekbadek**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes #1126
Closes #1148
Closes https://github.com/Automattic/newspack-newsletters/issues/645

### How to test the changes in this Pull Request:

1. On `master`, observe #1126 and another bug: when a campaign, tag, or category is assigned in the prompt edit modal, it still does show up in the autocomplete suggestions
2. Switch to this branch, observe that both bugs are fixed
3. Observe that during onboarding (Setup wizard), the footer copyright is not set to site tagline (as the default) (#1148)

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

File: assets/components/src/category-autocomplete/index.js [hunk 1]
```diff
@@ -107,21 +121,24 @@ class CategoryAutocomplete extends Component {
...
-		const { suggestions, allCategories } = this.state;
+		const { allCategories } = this.state;
 		const classes = classnames( 'newspack-category-autocomplete', className );
 		return (
 			<div className={ classes }>
 				<FormTokenField
 					onInputChange={ input => this.debouncedUpdateSuggestions( input ) }
 					value={ value.reduce( ( acc, item ) => {
-						const category =
+						const categoryOrItem =
```
Comment (miguelpeixe) [inline assets/components/src/category-autocomplete/index.js:131]: Non-blocking suggestion: normalize the `categoryOrItem` object in a separate function that ensures the return of `id` and `value` for better readability and maintainability.

**Review by miguelpeixe — APPROVED** [review]

File: assets/components/src/category-autocomplete/index.js (hunk 1 above)
Comment (adekbadek) [reply assets/components/src/category-autocomplete/index.js:131]: Good idea, but I'm not _entirely_ sold since I don't see how it could be reused. I'll leave it as it is for now.

**Comment by yogeshbeniwal** [comment]
@Automattic/newspack-product Is something wrong with release workflow, Many PRs like this are already released in v1.72.0 but then triggering another notification for 1.72.0-hotfix.1, while latest version is 1.75.

**Comment by dkoo** [comment]
@yogeshbeniwal I believe this is due to human error on our part, as we're adjusting to the new Git workflow. `hotfix` branches should be descended from `release`, not `master`, but we've had a few instances where one of us mistakenly creates a `hotfix` branch off of `master` (as was required in our old workflow). This results in a "bad" release asset being built. We've tried to go back and clean up these bad releases and tags, but doing so won't stop the notifications from occurring.
